#!/bin/bash -e

# Add perl6 to your PATH.
# https://github.com/nxadm/rakudo-pkg

BOURNE='PATH=~/.perl6/bin:/opt/rakudo-pkg/bin:/opt/rakudo-pkg/share/perl6/site/bin:$PATH; export PATH'
ZSH='path=(~/.perl6/bin /opt/rakudo-pkg/bin /opt/rakudo-pkg/share/perl6/site/bin $path[@])'

function add_to_path {
    CMD=$1
    FILE=$2
    if [ -z "`grep "$CMD" "$FILE"`" ]; then
        echo "$CMD" >> "$FILE"
        source $FILE
        echo
        echo "Added perl6 to PATH. You can activate the changes by typing:"
        echo "source $FILE"
        echo 
        else echo "PATH already in \"$FILE\". Skipped."
    fi
}

if [ -f "$HOME/.profile" ]; then
    add_to_path "$BOURNE" "$HOME/.profile"
    elif [ -f "$HOME/.bash_profile" ]; then
        add_to_path "$BOURNE" "$HOME/.bash_profile"
    elif [ -f "$HOME/.zshprofile" ]; then
        add_to_path "$ZSH" "$HOME/.zshprofile"
    elif [ -f "$HOME/.zshenv" ]; then
        add_to_path "$ZSH" "$HOME/.zshenv"
    else
        echo "Distribution not supported by this script."
        echo "Add these path manually to your PATH:"
        echo "- ~/.perl6/bin"
        echo "- /opt/rakudo-pkg/bin" 
        echo "- /opt/rakudo-pkg/share/perl6/site/bin"
fi

exit 0
