#!/bin/bash -e

RAKUDO_VERSION=$1
ZEF_VERSION=$2
BITS=$3

# Build Rakudo
curl -sSL -o rakudo.tar.gz \
https://github.com/rakudo/rakudo/releases/download/$RAKUDO_VERSION/rakudo-$RAKUDO_VERSION.tar.gz
tar -xzf rakudo.tar.gz
cd rakudo* 
perl Configure.pl --gen-moar --gen-nqp --backends=moar --relocatable
make test
make install

# Build Zef
git clone https://github.com/ugexe/zef.git 
cd zef
git checkout tags/$ZEF_VERSION
/rakudo-*/install/bin/perl6 -I. bin/zef install .

# Create links and add scripts
cd /rakudo*/install/bin
ln -s perl6 rakudo 
ln -s perl6 raku
ln -s ../share/perl6/site/bin/zef .
cp /install-zef-as-user .
cp /fix-windows10 .
cp /add-rakudo-to-path .

# Package it in /mnt
cd /rakudo*
mv install rakudo-$RAKUDO_VERSION
mkdir -p /staging
if [ "$BITS" == 64 ]; then
    $VARSTRING=${BIT}bit
    else $VARSTRING=${BIT}bit-nojit
fi
tar -czf /staging/rakudo-$RAKUDO_VERSION-linux-${VARSTRING}.tar.gz rakudo-$RAKUDO_VERSION

exit 0
