FROM centos:centos7
LABEL maintainer="Claudio Ramirez <pub.claudio@gmail.com>"

ENV LANG='en_US.UTF-8' \
pkgs='git perl-autodie perl-Digest-SHA redhat-lsb-core perl-IPC-Cmd' \
pkggroup='Development Tools' \
ruby_install_uri="https://github.com/postmodern/ruby-install.git" \
PATH="/opt/ruby/bin:/usr/local/bin:${PATH}"

RUN set -xv ; \
sed -i 's/enabled=1/enabled=0/g' /etc/yum/pluginconf.d/fastestmirror.conf && \
yum -q -y upgrade && \
ln -fs /usr/share/zoneinfo/Europe/Brussels /etc/localtime && \
# Packages for compiling and pkg creation
yum -q install -y ${pkgs} && \
yum -q groupinstall -y "${pkggroup}" && \
git clone $ruby_install_uri && \
/ruby-install/bin/ruby-install --install-dir /opt/ruby ruby && \
gem install --no-doc fpm && \
ln -s /usr/local/bin/fpm /usr/bin/ && \
# Cleanup
yum -q clean all && \
rm -rf /usr/lib/locale/locale-archive /usr/share/locale/* /ruby-install && \
localedef -i en_US -c -f UTF-8 en_US.UTF-8

COPY pkg_rakudo.pl /
COPY install-zef-as-user /
COPY fix-windows10 /
COPY add-rakudo-to-path /
COPY rakudo-pkg.sh /etc/profile.d/
COPY interp.c /

ENTRYPOINT [ "/pkg_rakudo.pl" ]
