FROM centos:centos6
LABEL maintainer="Claudio Ramirez <pub.claudio@gmail.com>"

ARG rakudo_release=2019.07.1
ARG zef_release=0.8.2
ENV LANG='en_US.UTF-8' \
ENV pkgs='git perl perl-core gcc make'

COPY install-zef-as-user /
COPY fix-windows10 /
COPY add-rakudo-to-path /
RUN ln -fs /usr/share/zoneinfo/Europe/Brussels /etc/localtime
RUN sed -i 's/enabled=1/enabled=0/g' /etc/yum/pluginconf.d/fastestmirror.conf
RUN yum -q -y upgrade && yum -q install -y ${pkgs} && yum -q clean all
RUN localedef -i en_US -c -f UTF-8 en_US.UTF-8

ENTRYPOINT /create-relocatable-build.sh $rakudo_release $zef_release 
