FROM centos:centos7
MAINTAINER Claudio Ramirez <pub.claudio@gmail.com>

ENV LANG=en_US.UTF-8 \
    packages='ruby-devel git wget redhat-lsb-core' \
    pkggroup='Development Tools'

RUN set -xv ; \
sed -i 's/enabled=1/enabled=0/g' /etc/yum/pluginconf.d/fastestmirror.conf && \
yum -q -y upgrade && \
ln -fs /usr/share/zoneinfo/Europe/Brussels /etc/localtime && \
# Packages for compiling and pkg creation
yum -q install -y $packages && yum -q groupinstall -y "$pkggroup" && \
gem install fpm && \
# Cleanup
yum -q clean all && \
rm -rf /usr/lib/locale/locale-archive /usr/share/locale/* && \
localedef -i en_US -c -f UTF-8 en_US.UTF-8

COPY pkg_rakudo /
COPY install_zef_as_user /
COPY install_zef_as_root /

CMD '/pkg_rakudo'
