FROM centos:centos6
LABEL maintainer="Claudio Ramirez <pub.claudio@gmail.com>"

ARG RAKUDO_VERSION
ARG ZEF_VERSION
ENV LANG='en_US.UTF-8'
ENV pkgs='git perl perl-core gcc make'

COPY create-relocatable-build /
COPY install-zef-as-user /
COPY fix-windows10 /
COPY add-rakudo-to-path /
RUN ln -fs /usr/share/zoneinfo/Europe/Brussels /etc/localtime
RUN sed -i 's/enabled=1/enabled=0/g' /etc/yum/pluginconf.d/fastestmirror.conf
RUN yum -y upgrade && yum install -y ${pkgs} && yum clean all
RUN localedef -i en_US -c -f UTF-8 en_US.UTF-8

ENTRYPOINT /create-relocatable-build $RAKUDO_VERSION $ZEF_VERSION 64
