FROM opensuse:42.3
LABEL maintainer="Claudio Ramirez <pub.claudio@gmail.com>"
ENV LANG='en_US.UTF-8' \
    pkgs='git gcc lsb5-core make rpm-build ruby wget' \
    pkgs_tmp='ruby-devel'

RUN set -xv ; \
    zypper refresh && \
    zypper update -y && \
    zypper install --replace-files -y ${pkgs} ${pkgs_tmp}
    ln -fs /usr/share/zoneinfo/Europe/Brussels /etc/localtime && \
    dnf -q groupinstall -y "${pkggroup}" && \
    gem install fpm && \
    zypper remove -y --clean-deps ${pkgs_tmp}

COPY pkg_rakudo.pl /
COPY install-zef-as-user /

ENTRYPOINT [ "/pkg_rakudo.pl" ]
