FROM debian:jessie
LABEL maintainer="Claudio Ramirez <pub.claudio@gmail.com>"

ENV LANG='C.UTF-8' \
DEBIAN_FRONTEND='noninteractive' \
TZ='Europe/Brussels' \
pkgs='curl build-essential git lsb-release' \
ruby_install_uri="https://github.com/postmodern/ruby-install.git" \
PATH="/opt/ruby/bin:/usr/local/bin:${PATH}"

RUN set -xv ; \
apt-get -qq update && \
apt-get -qq dist-upgrade -y && \
# pkgs for compiling and pkg creation
apt-get -qq install -y ${pkgs} && \
git clone $ruby_install_uri && \
/ruby-install/bin/ruby-install --install-dir /opt/ruby ruby && \
gem install --no-doc fpm && \
ln -s /opt/ruby/bin/fpm /usr/bin/ && \
# Cleanup
apt-get -qq autoremove -y && apt-get -qq clean && \
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /*.deb /MoarVM* /nqp* /rakudo*

COPY pkg_rakudo.pl /
COPY install-zef-as-user /
COPY fix-windows10 /
COPY add-rakudo-to-path /
COPY rakudo-pkg.sh /etc/profile.d/
COPY patch_oldgcc.sh /

ENTRYPOINT [ "/pkg_rakudo.pl" ]
