#!/bin/bash -e
set -xv

PKGDIR="/staging"

# Functions
function die { 
    echo "$1"
    exit 1
}

# Variables supplied by docker run
ERROR=""
[ -z "$MOARVM_VERSION" ] && ERROR+=$'MOARVM_VERSION not defined\n'
[ -z "$NQP_VERSION"    ] && ERROR+=$'NQP_VERSION not defined\n'
[ -z "$RAKUDO_VERSION" ] && ERROR+=$'RAKUDO_VERSION not defined\n'
[ -z "$REVISION"       ] && ERROR+=$'REVISION not defined\n'
if [ ! -z "$ERROR" ]; then die "$ERROR"; fi

MAINTAINER=${MAINTAINER:-"Claudio Ramirez <pub.claudio@gmail.com>"}

# Internal variables
URL_BASE="https://rakudo.perl6.org/downloads"               
URL_NQP="${URL_BASE}/nqp/nqp-${NQP_VERSION}.tar.gz"
URL_RAKUDO="${URL_BASE}/rakudo/rakudo-${RAKUDO_VERSION}.tar.gz"
URL_MOARVM="https://moarvm.org/releases/MoarVM-${MOARVM_VERSION}.tar.gz"
PREFIX=/opt/rakudo-pkg
if [ -f "/etc/debian_version" ]; then
    TARGET=deb
    INSTALL="dpkg -i"
elif [ -f "/etc/redhat-release" ]; then 
    TARGET="rpm"
    INSTALL="rpm -Uvh"
else
    echo "OS not yet supported."
    exit 1
fi

# Download and compile sources
for i in $URL_MOARVM $URL_NQP $URL_RAKUDO; do wget $i; done 
for i in *.tar.gz; do tar xzf $i; rm -rf $i; done
cd /MoarVM*; perl Configure.pl --prefix=$PREFIX
make && make install
cd /nqp-*; perl Configure.pl --backends=moar --prefix=$PREFIX
make && make test && make install
cd /rakudo-*; perl Configure.pl --backends=moar --prefix=$PREFIX
make && make test && make install
mv /install_zef_* $PREFIX/bin
if [ -f "/fix_windows10" ]; then mv /fix_windows10 $PREFIX/bin; fi
cd /
rm -rf /MoarVM* /nqp* /rakudo* 
echo "Rakudo was succesfully compiled."

# Packaging
OS=$(lsb_release -is)
RELEASE=$(lsb_release -rs)
if [ ! -d "$PKGDIR" ]; then mkdir -p "$PKGDIR"; fi
fpm \
--deb-no-default-config-files \
--license "Artistic License 2.0" \
--description "Rakudo is a compiler for the Perl 6 programming language" \
-s dir \
-t $TARGET \
-p $PKGDIR \
-n rakudo-pkg \
-m "$MAINTAINER" \
-v $RAKUDO_VERSION \
--iteration $REVISION \
--url "https://perl6.org" \
$PREFIX

# Add OS info to filename
cd $PKGDIR
mv *.$TARGET $(ls -1 *.$TARGET |perl -lwp -e "s/rakudo-pkg/rakudo-pkg-$OS$RELEASE/")
PKG=$(ls -1 *.$TARGET)
sha1sum $PKG > $PKG.sha1
cat $PKG.sha1

# Test it by installing it
$INSTALL $PKG

# Run it
$PREFIX/bin/perl6 -v

# Install zef as root
cd /var/tmp
git clone https://github.com/ugexe/zef.git
cd zef
$PREFIX/bin/perl6 -Ilib bin/zef --install-to=perl install .
rm -f $PREFIX/bin/zef
ln -s $PREFIX/share/perl6/bin/zef $PREFIX/bin/zef
rm -rf /var/tmp/zef

exit 0
